window.articlesData = [
  {
    "id": "1",
    "date": "2025-05-01",
    "title": "Spring Tournament Kicks Off with Record Attendance",
    "content": "The Data Guys Archery Club kicked off its annual Spring Tournament on May 1, 2025, with an unprecedented turnout of over 120 archers, marking a new record for the club. Held at the newly opened outdoor range, the day-long event brought together competitors of all experience levels, from beginners taking their first shots to seasoned archers aiming for the top prizes. The tournament featured a variety of formats, including target archery and a fun 3D archery challenge with lifelike animal targets set up across the field. Master Bowman Rob McKenzie, who has been overseeing the club’s events for over 30 years, ensured the day ran smoothly, with volunteers managing scoring and safety protocols. Participants enjoyed a sunny spring day, with clear skies and a light breeze adding a layer of challenge to the shots. The event also included a small vendor fair where local archery shops showcased the latest bows, arrows, and accessories, drawing significant interest from attendees. Families and friends gathered to cheer on the competitors, creating a lively, community-focused atmosphere. The tournament concluded with an awards ceremony, where top scorers in each category received medals and gift cards to local sporting goods stores. For many, the highlight was the junior division, where young archers showed impressive skill and sportsmanship. The club plans to use the success of this event as a springboard for future tournaments, with hopes of attracting even more participants next year. Feedback from attendees was overwhelmingly positive, with many praising the organization and welcoming environment. The Data Guys Archery Club continues to solidify its reputation as a hub for archery enthusiasts in the region.",
    "category": "Tournament",
    "brief": "The Data Guys Archery Club kicked off its annual Spring Tournament on May 1, 2025, with an unprecedented turnout"
  },
  {
    "id": "2",
    "date": "2025-04-22",
    "title": "Beginner Workshop Opens New Doors",
    "content": "On April 22, 2025, the Data Guys Archery Club hosted its monthly beginner’s workshop, welcoming 25 newcomers eager to learn the art of archery. The three-hour session, led by Master Bowman Rob McKenzie and a team of experienced instructors, focused on foundational skills to ensure participants could shoot safely and confidently. The workshop began with a detailed safety briefing, covering range rules, proper handling of equipment, and how to avoid common mistakes. Participants were then introduced to the basics of archery form, including stance, grip, and aiming techniques, with instructors providing hands-on guidance to correct posture and improve accuracy. Each attendee was paired with a mentor to ensure personalized attention, which proved especially helpful for those who had never held a bow before. The club provided all necessary equipment, including recurve bows and arrows, allowing participants to focus on learning without worrying about gear. By the end of the session, every beginner had the chance to shoot at targets from 10 yards, with many hitting the mark on their first try—a thrilling moment for the group. The workshop also included a Q&A segment, where participants asked about everything from bow maintenance to the mental focus required in competitive archery. Several attendees expressed interest in joining the club’s regular training sessions, with a few signing up for the upcoming ‘Come & Try’ course. The event fostered a sense of camaraderie, as participants bonded over shared challenges and successes. The Data Guys Archery Club continues to prioritize accessibility, ensuring that anyone with an interest in archery can take their first steps in a supportive environment. This workshop is part of a broader effort to grow the sport locally.",
    "category": "Training",
    "brief": "On April 22, 2025, the Data Guys Archery Club hosted its monthly beginner’s workshop"
  },
  {
    "id": "3",
    "date": "2025-03-18",
    "title": "Junior League Celebrates Milestone Season",
    "content": "The Data Guys Archery Club celebrated a significant milestone on March 18, 2025, as its Junior League wrapped up its 10th season with a memorable fun shoot and awards night. The event brought together over 40 young archers, aged 8 to 16, who had spent the past three months training and competing in weekly matches. The season focused on developing skills, teamwork, and sportsmanship, with coaches emphasizing the importance of effort over results. The fun shoot featured creative challenges, such as shooting at moving targets and a balloon-popping contest, which had the kids laughing and cheering for one another. The evening transitioned into an awards ceremony, where participants were recognized for their achievements. Categories included Most Improved, Best Sportsmanship, and Top Scorer, with each winner receiving a custom-engraved medal and a certificate. One standout moment was when 12-year-old Emily Carter was awarded the Sportsmanship Award for her consistent encouragement of her peers, even during tough matches. Parents and families filled the club’s indoor range, applauding the young archers and sharing a potluck dinner that added to the festive atmosphere. The Junior League has grown significantly since its inception, becoming a cornerstone of the club’s youth programs. Coaches noted the impressive progress of the group, with many juniors now able to shoot accurately at 20 yards—a remarkable feat for their age. The event also included a slideshow of photos from the season, highlighting training sessions, competitions, and team-building activities. The Data Guys Archery Club plans to expand the Junior League next season by adding more advanced training modules and hosting inter-club matches with other local youth teams. For now, the club celebrates a decade of fostering the next generation of archers with pride and optimism for the future.",
    "category": "Youth Program",
    "brief": "The Data Guys Archery Club celebrated a significant milestone on March 18, 2025, as its Junior League wrapped up its 10th season"
  },
  {
    "id": "4",
    "date": "2025-05-05",
    "title": "New Outdoor Range Officially Opens",
    "content": "On May 5, 2025, the Data Guys Archery Club proudly opened its state-of-the-art outdoor range, a project that had been in development for over a year. The new facility, located just behind the club’s main building, spans 5 acres and features 20 shooting lanes with adjustable targets ranging from 10 to 70 yards, catering to archers of all skill levels. The range is equipped with weather shelters, allowing members to shoot comfortably in rain or shine, and includes a shaded seating area for spectators. During the opening ceremony, club president Sarah Thompson cut the ribbon while over 50 members and local dignitaries looked on. The event featured a demonstration shoot by Master Bowman Rob McKenzie, who showcased the range’s capabilities by hitting a bullseye from 70 yards, earning enthusiastic applause. Members were then invited to test the range, with beginners trying shorter distances and advanced archers tackling the longer lanes. The adjustable targets, which can be moved via a pulley system, were a particular hit, as they allowed for quick changes between rounds. The range also includes a dedicated 3D archery section with lifelike animal targets, adding an element of fun and realism for those training for hunting or competitive events. Safety was a top priority in the design, with high netting around the perimeter and clear signage for range rules. The club invested in eco-friendly materials, using recycled wood for the shelters and biodegradable target backstops. Members have already praised the facility for its versatility and accessibility, with many noting how it enhances their training experience. The Data Guys Archery Club expects the outdoor range to become a regional hub for archery, with plans to host tournaments and workshops in the coming months. This opening marks a significant milestone in the club’s growth.",
    "category": "Facilities",
    "brief": "The Data Guys Archery Club proudly opened its state-of-the-art outdoor range"
  },
  {
    "id": "5",
    "date": "2025-04-10",
    "title": "Inclusive Archery Night Draws Diverse Crowd",
    "content": "The Data Guys Archery Club hosted its first-ever Inclusive Archery Night on April 10, 2025, welcoming a diverse group of participants for an evening of learning and community building. Over 60 people attended, representing a wide range of backgrounds, ages, and abilities, including individuals with physical disabilities, members of the LGBTQ+ community, and families from underserved neighborhoods. The event was designed to make archery accessible to everyone, with adaptive equipment like seated shooting stations and lighter bows available for those who needed them. Instructors, including Master Bowman Rob McKenzie, provided one-on-one guidance, ensuring each participant could shoot safely and enjoyably. The evening began with a group icebreaker, where attendees shared their reasons for joining—many expressed a lifelong curiosity about archery but had never felt comfortable trying it until now. The range buzzed with excitement as participants took their first shots, with cheers erupting each time someone hit the target. Volunteers set up a mini-competition with prizes like club merchandise, fostering a lighthearted atmosphere. A highlight was the story of 45-year-old Maria Gonzalez, who uses a wheelchair and hit the bullseye on her third shot, inspiring others with her determination. The event also featured a potluck dinner, with attendees bringing dishes from their cultures, ranging from empanadas to samosas, which sparked conversations and new friendships. The club partnered with local organizations to promote the event, ensuring broad outreach. Feedback was overwhelmingly positive, with many requesting that Inclusive Archery Night become a regular occurrence. The Data Guys Archery Club is committed to fostering an inclusive environment, and this event was a meaningful step toward that goal. Plans are already underway for the next event, with hopes of reaching even more community members in the future.",
    "category": "Community",
    "brief": "The Data Guys Archery Club hosted its first-ever Inclusive Archery Night on April 10, 2025, welcoming a diverse group of participants for an evening of learning"
  },
  {
    "id": "6",
    "date": "2025-03-02",
    "title": "Club Hosts Friendly Against Riverside Archers",
    "content": "On March 2, 2025, the Data Guys Archery Club welcomed the Riverside Archers for a friendly competition that emphasized camaraderie over rivalry. Held at the club’s indoor range, the event drew 30 participants from both teams, competing in a mixed-format shoot that included target archery, a speed round, and a novelty balloon-popping challenge. The day began with a warm welcome from club president Sarah Thompson, who highlighted the importance of building connections between local archery communities. Teams were paired into mixed groups, allowing members to meet and share tips as they shot side by side. The speed round, where archers had 30 seconds to shoot as many arrows as possible, brought laughter and cheers, especially when one archer accidentally popped a balloon meant for the next event. Master Bowman Rob McKenzie oversaw the scoring, ensuring fairness while keeping the mood light. Between rounds, participants enjoyed a spread of snacks, including homemade cookies and fruit, which gave everyone a chance to relax and chat about their love for the sport. The balloon-popping challenge was a crowd favorite, with archers taking aim at colorful balloons pinned to targets—each pop earning a small prize like a keychain or sticker. The event wrapped up with a group photo and an exchange of club patches, a gesture of goodwill between the two teams. Riverside Archers’ captain, Tom Ellis, praised the Data Guys for their hospitality, noting how the event reminded everyone that archery is as much about community as it is about competition. Both clubs agreed to make this an annual tradition, with Riverside hosting the next meetup. The Data Guys Archery Club continues to strengthen ties within the regional archery scene, fostering friendships that enrich the sport for all involved.",
    "category": "Events",
    "brief": "The Data Guys Archery Club welcomed the Riverside Archers for a friendly competition that emphasized camaraderie over rivalry"
  },
  {
    "id": "7",
    "date": "2025-05-08",
    "title": "Archery Gear Swap Meet a Success",
    "content": "The Data Guys Archery Club organized a highly successful gear swap meet on May 8, 2025, providing members with an affordable way to upgrade their equipment. Held in the club’s outdoor pavilion, the event attracted over 50 participants who brought bows, arrows, quivers, and other accessories to trade or sell. Tables were set up with items neatly displayed, and members mingled, inspecting gear and negotiating trades. One highlight was a barely used recurve bow that a beginner swapped for a set of training arrows, a deal both parties were thrilled about. The club also invited a local archery shop to set up a booth, offering discounted accessories and free bow-tuning services, which drew a steady crowd. Master Bowman Rob McKenzie gave a short talk on how to evaluate used gear, sharing tips on checking for wear and ensuring quality, which many attendees found invaluable. A sense of community filled the air as members shared stories about their favorite pieces of equipment—like a vintage quiver one archer had inherited from their grandfather. The event wasn’t just about trading; it was also an opportunity for newer members to learn from veterans about what gear suits their needs as they progress in the sport. The club set up a small shooting range nearby, allowing participants to test out their new gear immediately, which led to plenty of smiles and friendly competition. By the end of the day, nearly every attendee left with something new, and several pieces of unclaimed gear were donated to the club’s youth program. The swap meet not only promoted sustainability by encouraging equipment reuse but also strengthened the club’s tight-knit community. Due to its success, the Data Guys Archery Club plans to make the gear swap an annual event, with hopes of involving more local clubs next time.",
    "category": "Community",
    "brief": "The Data Guys Archery Club organized a successful gear swap meet on May 8, 2025, providing members with an affordable way to upgrade their equipment."
  },
  {
    "id": "8",
    "date": "2025-04-28",
    "title": "Advanced Technique Clinic Held",
    "content": "On April 28, 2025, the Data Guys Archery Club hosted an Advanced Technique Clinic for experienced archers looking to refine their skills. The four-hour session, attended by 15 members, was led by Master Bowman Rob McKenzie, who focused on precision aiming, shooting in windy conditions, and mental focus under pressure. The clinic began with a discussion on fine-tuning form, where Rob demonstrated how small adjustments to grip and anchor points can drastically improve consistency. Participants then moved to the outdoor range to practice shooting in simulated wind conditions, using fans to create a breeze while aiming at targets 50 yards away. Rob shared strategies for compensating for wind drift, such as adjusting aim and timing the release during lulls in the gusts. The group also worked on mental conditioning, with exercises designed to build focus and reduce performance anxiety, such as visualizing shots before taking them. Each archer received personalized feedback, with Rob observing their shots and offering tailored advice—one member discovered that a slight tilt in their stance was throwing off their accuracy. The clinic included a competitive element, with a mini-tournament where participants shot 10 arrows under timed conditions, mimicking the pressure of a real event. Scores were close, and the winner received a club-branded quiver as a prize. Attendees appreciated the hands-on approach, noting how the clinic helped them identify and address weaknesses in their technique. The session ended with a Q&A, where topics ranged from bow tuning to strategies for long-distance shooting. The Data Guys Archery Club plans to offer more advanced clinics in the future, potentially bringing in guest instructors to provide fresh perspectives. For now, the participants left feeling more confident and equipped to take their archery to the next level in upcoming competitions.",
    "category": "Training",
    "brief": "The Data Guys Archery Club hosted an Advanced Technique Clinic for experienced archers looking to refine their skills"
  },
  {
    "id": "9",
    "date": "2025-04-15",
    "title": "Family Archery Day Brings Smiles",
    "content": "The Data Guys Archery Club hosted a Family Archery Day on April 15, 2025, bringing together over 80 participants for a day of fun, learning, and bonding. The event, held at the club’s outdoor range, was designed to introduce families to archery in a relaxed and playful environment. The day kicked off with a safety briefing tailored for all ages, ensuring even the youngest participants understood the basics of range etiquette. Instructors set up multiple stations, each offering a different activity: one for beginners to learn basic shooting techniques, another with balloon targets for a popping contest, and a third featuring a treasure hunt where kids shot at targets to reveal clues. Children as young as 5 took part, using lightweight bows, while parents and older siblings tried their hand at longer distances. The club provided all equipment, making it easy for families to participate without prior investment. Laughter filled the air as families cheered each other on, with one memorable moment being a father-son duo hitting the bullseye together on their first try. Volunteers organized games like an archery relay, where teams of family members took turns shooting to earn points, fostering teamwork and excitement. A picnic lunch was served, with families spreading out on blankets to enjoy sandwiches, fruit, and homemade lemonade while sharing stories of their experiences. The event also included a short demo by the club’s junior league members, who showcased their skills and inspired the younger attendees. Many families expressed interest in joining the club’s regular programs, with several signing up for the ‘Come & Try’ course on the spot. The Data Guys Archery Club’s Family Archery Day succeeded in its goal of making the sport accessible and enjoyable for all, strengthening community ties in the process.",
    "category": "Events",
    "brief": "The Data Guys Archery Club hosted a Family Archery Day on April 15, 2025, bringing together over 80 participants for a day of fun"
  },
  {
    "id": "10",
    "date": "2025-03-25",
    "title": "Youth Archery Camp Announced",
    "content": "The Data Guys Archery Club announced its upcoming Youth Archery Camp on March 25, 2025, set to take place during the summer break. Designed for children aged 8 to 14, the week-long camp aims to teach archery fundamentals while emphasizing teamwork, discipline, and outdoor fun. The program will run from July 14 to July 18, with daily sessions from 9:00 AM to 3:00 PM at the club’s outdoor range. Led by Master Bowman Rob McKenzie and a team of certified instructors, the camp will cover everything from basic shooting techniques to more advanced skills like aiming at moving targets. Each day will include structured lessons, such as proper stance, bow handling, and safety protocols, followed by hands-on practice at various distances. The camp will also feature team-building activities, such as relay races and group challenges, to help campers build friendships and learn to work together. A highlight will be the 3D archery day, where kids will shoot at lifelike animal targets in a simulated forest setting, making the experience both educational and exciting. The club is providing all equipment, ensuring accessibility for families new to the sport, though campers are welcome to bring their own bows if they have them. Daily lunches and snacks will be included, with options for dietary restrictions. The camp will conclude with a mini-tournament, where participants can showcase their new skills and compete for prizes like medals and club merchandise. Parents will be invited to attend the final day to cheer on their children and see their progress. The Data Guys Archery Club expects high demand, with spots limited to 30 campers to ensure personalized attention. Registration is now open, and early sign-ups are encouraged to secure a place in what promises to be a memorable experience for young archers.",
    "category": "Youth Program",
    "brief": "The Data Guys Archery Club announced its upcoming Youth Archery Camp on March 25, 2025"
  },
  {
    "date": "2025-05-03",
    "title": "Club Upgrades Indoor Lighting",
    "content": "On May 3, 2025, the Data Guys Archery Club completed a major upgrade to its indoor range, installing new LED lighting to enhance visibility and improve the shooting experience. The project, which took two weeks to complete, replaced the outdated fluorescent lights with energy-efficient LEDs that provide brighter, more consistent illumination across all 15 shooting lanes. The new lights are adjustable, allowing the club to create optimal conditions for different activities, from casual practice to competitive events. Members immediately noticed the difference during the first evening shoot after the upgrade, with many commenting on how the improved lighting made it easier to see their targets, especially at longer distances like 30 yards. The LEDs also reduce glare, a common issue with the old system, which had caused eye strain for some archers during extended sessions. Club president Sarah Thompson explained that the upgrade was part of a broader effort to modernize the facility and ensure it meets the needs of all members. The installation was carried out by a local contractor, with funding coming from a combination of club savings and a small grant from the city’s recreational improvement program. In addition to better visibility, the new lights are expected to lower energy costs by 20%, aligning with the club’s commitment to sustainability. To celebrate the upgrade, the club hosted a glow-in-the-dark archery night, dimming the lights slightly and using fluorescent targets and arrows for a fun, unique experience. The event drew a large crowd, with members of all ages enjoying the creative twist on their usual practice. The Data Guys Archery Club plans to continue investing in facility improvements, with future projects potentially including upgraded target stands and expanded seating for spectators.",
    "category": "Facilities",
    "brief": "The Data Guys Archery Club completed a major upgrade to its indoor range, installing new LED lighting to enhance visibility and improve the shooting experience."
  },
  {
    "id": "11",
    "date": "2025-04-05",
    "title": "Charity Shoot Raises Funds",
    "content": "The Data Guys Archery Club held a Charity Shoot on April 5, 2025, raising $500 for local community programs in a heartwarming display of generosity. The event, which took place at the club’s outdoor range, attracted over 40 participants who paid a small entry fee to compete in a series of fun archery challenges. All proceeds were donated to a local nonprofit that provides after-school programs for underprivileged youth, a cause the club has supported for years. The shoot featured three rounds: a standard target competition, a speed shoot where archers aimed to hit as many targets as possible in 60 seconds, and a trick shot challenge involving balloons and small moving targets. Master Bowman Rob McKenzie emceed the event, keeping spirits high with his encouraging commentary and humorous anecdotes about past charity shoots. Participants ranged from seasoned archers to beginners, with many bringing their families to cheer them on. The club provided refreshments, including lemonade and cookies, which were sold for additional donations, adding to the total funds raised. A raffle was also held, with prizes like archery lessons and club merchandise, further boosting contributions. One memorable moment came when a 10-year-old junior member, Liam Carter, won the trick shot challenge by popping three balloons in a row, earning a standing ovation. The event fostered a strong sense of community, with participants sharing stories about how archery has impacted their lives and why they were proud to support the cause. The $500 will help fund educational supplies and sports equipment for the nonprofit’s programs, directly benefiting local kids. The Data Guys Archery Club plans to make the Charity Shoot an annual event, with hopes of raising even more next year while continuing to give back to the community.",
    "category": "Community",
    "brief": "The Data Guys Archery Club held a Charity Shoot on April 5, 2025, raising $500 for local community programs in a heartwarming display of generosity."
  },
  {
    "id": "12",
    "date": "2025-03-15",
    "title": "Winter League Finals Conclude",
    "content": "The Data Guys Archery Club concluded its Winter League on March 15, 2025, with an exciting finals event that showcased the talent of its top archers. The league, which ran for eight weeks, brought together 25 members who competed in weekly matches at the indoor range, battling cold weather and tight competition to earn points toward the championship. The finals pitted the top eight archers against each other in a head-to-head format, with each round consisting of 15 arrows shot at 20 yards. The atmosphere was electric, with spectators filling the stands to cheer on their friends and family. Master Bowman Rob McKenzie officiated, ensuring fair play while offering tips to competitors between rounds. The final match came down to a nail-biting showdown between veteran archer Claire Nguyen and 16-year-old prodigy James Lee, with Claire ultimately winning by just two points after a perfect final shot. Winners received custom-engraved trophies and gift cards to a local archery shop, while all participants were awarded certificates for their dedication. The event also featured a catered lunch, with hot soup and sandwiches providing a warm respite from the chilly March day. Throughout the league, participants showed remarkable improvement, with many citing the consistent practice and friendly rivalry as key to their growth. The Winter League also served as a training ground for upcoming regional tournaments, with several archers planning to represent the club in spring competitions. A highlight for many was the sense of camaraderie that developed over the weeks, as competitors became close friends, sharing tips and celebrating each other’s successes. The Data Guys Archery Club looks forward to the next season, with plans to expand the league by adding more divisions to accommodate growing interest.",
    "category": "Tournament",
    "brief": "The Data Guys Archery Club concluded its Winter League on March 15, 2025, with an exciting finals event that showcased the talent of its top archers."
  },
  {
    "id": "13",
    "date": "2025-04-18",
    "title": "Bow Maintenance Workshop Hosted",
    "content": "On April 18, 2025, the Data Guys Archery Club hosted a Bow Maintenance Workshop, teaching 20 members how to care for and tune their equipment. Led by Master Bowman Rob McKenzie, the three-hour session covered essential skills to keep bows in top condition, ensuring better performance and longevity. The workshop began with a lesson on string maintenance, where Rob demonstrated how to inspect for fraying, apply wax, and replace strings safely. Participants then learned how to check and adjust the brace height, a critical factor in a bow’s accuracy and power, using a simple bow square tool. Rob also explained how to balance a bow by adjusting the limbs and aligning the sight, offering tips on spotting common issues like limb twist. Each attendee worked on their own bow, with Rob and his team providing hands-on assistance—one member discovered their bowstring had been improperly installed, which had been affecting their shots for months. The workshop also covered arrow maintenance, including how to fletch arrows and inspect shafts for cracks. A Q&A session allowed participants to ask about specific problems, with topics ranging from recurve bow tuning to caring for compound bows. The club provided a maintenance kit to each attendee, including wax, a stringer, and a small wrench set, ensuring they could continue practicing what they learned. Many participants noted how empowering it felt to understand their equipment better, with one archer saying they felt more confident heading into their next competition. The event ended with a group discussion on the importance of regular maintenance in preventing costly repairs. The Data Guys Archery Club plans to host more workshops like this, potentially expanding to cover advanced tuning techniques for competitive archers in the future.",
    "category": "Training",
    "brief": "On April 18, 2025, the Data Guys Archery Club hosted a Bow Maintenance Workshop, teaching 20 members how to care for and tune their equipment."
  },
  {
    "id": "14",
    "date": "2025-05-10",
    "title": "Annual Club Picnic Planned",
    "content": "The Data Guys Archery Club announced its Annual Club Picnic on May 10, 2025, promising a day of archery, food, and member bonding at the outdoor range. Scheduled for June 15, the event will run from 11:00 AM to 4:00 PM and is open to all members and their families, with an expected turnout of over 100 people. The picnic will feature a variety of archery activities, including a fun shoot with novelty targets like watermelons and a family relay where teams compete to hit the most bullseyes. For those new to the sport, instructors will offer mini-lessons, ensuring everyone can participate regardless of experience. The club is providing all equipment, though members are welcome to bring their own bows. A potluck-style lunch will be the centerpiece, with the club supplying grilled burgers and hot dogs while attendees contribute sides, desserts, and drinks—last year’s picnic saw a spread that included everything from homemade pies to vegan salads. Lawn games like cornhole and frisbee will be set up for non-archery entertainment, and a shaded area with picnic tables will offer a place to relax and socialize. The event will also include a short awards ceremony to honor members who have contributed to the club over the past year, such as volunteer coaches and event organizers. Master Bowman Rob McKenzie will lead a group trick shot demonstration, a tradition that always draws a crowd with its impressive displays of skill. The picnic is a chance for members to connect outside of formal training, strengthening the club’s tight-knit community. The Data Guys Archery Club encourages early RSVPs to help with planning, and a small donation is requested to cover costs. This annual tradition continues to be a highlight of the club’s calendar, bringing members together to celebrate their shared passion.",
    "category": "Events",
    "brief": "The Data Guys Archery Club announced its Annual Club Picnic on May 10, 2025"
  }
];